#配置tomcat参数 语法为key: value(value前必须有个空格)
server:
  port: 8081
  servlet:
    path: /test
#配置普通参数
age: 13

nj:
  name: nanjiang
  age: 24
  zl: 140

#配置普通对象
person:
  name: zhangsan
  age: 14
  address: China
#或者
person2: {name: lisi,age: 15,address: Chinese}

#配置map
map:
  key1: value1
  key2: value2

#配置List、Set数据
city:
- xian
- xianyang
- shanghai
- shenzhen
city2: {xianyang,xian,shanghai,beijing}

#集合当中的元素是对象形式
student:
- name: zhangsan
  age: 20
  score: 100
- name: lisi
  age: 21
  score: 99
- name: wangwu
  age: 22
  score: 96